### ISSUE TITLE
Unix time stamp, with no network connection.

### ISSUE THREAD

**Issue by danems11** [BYU-MAGICC/fcu_io2#46]
With no network connection, It thinks the date is Jan 1 1970. Which creates an error in our naze "std::runtime_error" Time is out of dual 32-bit range

**Comment by superjax** [comment]
This is definitely related to http://answers.ros.org/question/209452/exception-thrown-while-processing-service-call-time-is-out-of-dual-32-bit-range/

**Comment by superjax** [comment]
I'm not sure which line of the code is causing this.  From that ROS discussion, it appears to be happening when you do subtractions and additions with time.  I suspect that somehow we are asking for a negative time somewhere.  To track down this issue, we will have to use some `try - catch` logic to figure out exactly which line is causing the bug.

**Comment by el3ment** [comment]
Does this happen when you lose a network connection (i.e you had one, and
it dropped) or if you start with no connection?

**Comment by superjax** [comment]
It's when they start without a network connection.  The real issue is that their computer time is Jan 1 1970, so `ros::Time::now() == 0`.

Ahaha!  I think just figured it out in writing this.  If the naze was started somehow before the raspberry pi, then the time offset would be negative, and would overrun the `uint64_t` and give that error.  I still need to track down which line could cause this, but I bet that's what is happening.

**Comment by superjax** [comment]
This seems to have been resolved
